title: "Hardcore trial & error"
description: "My journey through code and development"
url: "https://jestersimpps.github.io"
baseurl: ""

author:
  name: "Jester Simpps"
  email: "jestersimpps@gmail.com"
  twitter: "jestersimpps"
  github: "jestersimpps"
  linkedin: "jo-vinkenroye/63/a79/459"
  instagram: "jestersimpps"

markdown: kramdown
highlighter: rouge
permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jester Simpps"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - index.html.bak

include:
  - automated-e2e-api-testing-documentation-for-node-js
  - decentralized-microservices-with-ipfs
  - experimenting-with-google-spreadsheets-assemble-io-and-internationalisation
  - from-gulp-to-webpack
  - getting-around-the-product-variant-limitation-in-shopify
  - getting-started-with-microservices-and-go
  - gitup-the-new-git-manager
  - my-first-experience-with-bitpay-bitcore
  - setting-up-a-private-npm-registry-with-sinopia
  - smart-contract-blockchain-platforms
  - theme-setup
  - webstorm-vs-atom
  - a-cool-idea-for-scrolling-throough-posts
  - page2
  - page3
  - posts
  - tags
  - about
